# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subtrigger}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Arjan van der Gaag"]
  s.date = %q{2010-02-18}
  s.default_executable = %q{subtrigger}
  s.description = %q{This gem allows you to create simple Ruby triggers for Subversion commit messages, responding to keywords in your log messages to send e-mails, deploy sites or do whatever you need.}
  s.email = %q{arjan@arjanvandergaag.nl}
  s.executables = ["subtrigger"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/subtrigger",
     "lib/subtrigger.rb",
     "lib/subtrigger/email.rb",
     "lib/subtrigger/repository.rb",
     "lib/subtrigger/trigger.rb",
     "test/helper.rb",
     "test/test_email.rb",
     "test/test_repository.rb",
     "test/test_subtrigger.rb",
     "test/test_trigger.rb"
  ]
  s.homepage = %q{http://github.com/avdgaag/subtrigger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Create post-commit triggers for Subversion commit messages}
  s.test_files = [
    "test/helper.rb",
     "test/test_email.rb",
     "test/test_repository.rb",
     "test/test_subtrigger.rb",
     "test/test_trigger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

